// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'cast.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `collect_ssdp_responses`, `create_ssdp_socket`, `extract_location`, `get_av_url`, `get_local_ip`, `get_rc_url`, `parse_device_xml`, `send_soap_action`, `try_broadcast_ssdp`, `try_multicast_ssdp`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `fmt`, `fmt`

Future<List<ProjectorInfo>> scanProjectors({required BigInt timeoutSecs}) =>
    RustLib.instance.api.crateApiCastScanProjectors(timeoutSecs: timeoutSecs);

Future<void> wakeOnLan({required String macAddress}) =>
    RustLib.instance.api.crateApiCastWakeOnLan(macAddress: macAddress);

@freezed
sealed class ProjectorInfo with _$ProjectorInfo {
  const ProjectorInfo._();
  const factory ProjectorInfo({
    required String friendlyName,
    required String ip,
    required String locationXmlUrl,
    String? avTransportUrl,
    String? renderingControlUrl,
  }) = _ProjectorInfo;

  /// 投送视频 (SetAVTransportURI + Play)
  Future<void> castVideo({required String videoUrl}) => RustLib.instance.api
      .crateApiCastProjectorInfoCastVideo(that: this, videoUrl: videoUrl);

  /// 获取播放进度 (当前时长, 总时长) 格式 HH:MM:SS
  Future<(String, String)> getPositionInfo() =>
      RustLib.instance.api.crateApiCastProjectorInfoGetPositionInfo(
        that: this,
      );

  /// 获取播放进度 (当前秒数, 总秒数)
  Future<(BigInt, BigInt)> getPositionInfoSec() =>
      RustLib.instance.api.crateApiCastProjectorInfoGetPositionInfoSec(
        that: this,
      );

  /// 获取传输状态
  Future<TransportState> getTransportInfo() =>
      RustLib.instance.api.crateApiCastProjectorInfoGetTransportInfo(
        that: this,
      );

  /// 获取当前音量
  Future<int> getVolume() =>
      RustLib.instance.api.crateApiCastProjectorInfoGetVolume(
        that: this,
      );

  /// 暂停
  Future<void> pause() => RustLib.instance.api.crateApiCastProjectorInfoPause(
        that: this,
      );

  /// 播放
  Future<void> play() => RustLib.instance.api.crateApiCastProjectorInfoPlay(
        that: this,
      );

  /// 进度跳转 - target_time 格式为 HH:MM:SS
  Future<void> seek({required String targetTime}) => RustLib.instance.api
      .crateApiCastProjectorInfoSeek(that: this, targetTime: targetTime);

  /// 设置静音状态
  Future<void> setMute({required bool mute}) => RustLib.instance.api
      .crateApiCastProjectorInfoSetMute(that: this, mute: mute);

  /// 设置音量 (0-100)
  Future<void> setVolume({required int volume}) => RustLib.instance.api
      .crateApiCastProjectorInfoSetVolume(that: this, volume: volume);

  /// 停止
  Future<void> stop() => RustLib.instance.api.crateApiCastProjectorInfoStop(
        that: this,
      );
}

enum TransportState {
  stopped,
  playing,
  paused,
  transitioning,
  noMedia,
  unknown,
  ;
}
