// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/cast.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 496271499;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rusty_dlna',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiCastProjectorInfoCastVideo(
      {required ProjectorInfo that, required String videoUrl});

  Future<(String, String)> crateApiCastProjectorInfoGetPositionInfo(
      {required ProjectorInfo that});

  Future<(BigInt, BigInt)> crateApiCastProjectorInfoGetPositionInfoSec(
      {required ProjectorInfo that});

  Future<TransportState> crateApiCastProjectorInfoGetTransportInfo(
      {required ProjectorInfo that});

  Future<int> crateApiCastProjectorInfoGetVolume({required ProjectorInfo that});

  Future<void> crateApiCastProjectorInfoPause({required ProjectorInfo that});

  Future<void> crateApiCastProjectorInfoPlay({required ProjectorInfo that});

  Future<void> crateApiCastProjectorInfoSeek(
      {required ProjectorInfo that, required String targetTime});

  Future<void> crateApiCastProjectorInfoSetMute(
      {required ProjectorInfo that, required bool mute});

  Future<void> crateApiCastProjectorInfoSetVolume(
      {required ProjectorInfo that, required int volume});

  Future<void> crateApiCastProjectorInfoStop({required ProjectorInfo that});

  Future<List<ProjectorInfo>> crateApiCastScanProjectors(
      {required BigInt timeoutSecs});

  Future<void> crateApiCastWakeOnLan({required String macAddress});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiCastProjectorInfoCastVideo(
      {required ProjectorInfo that, required String videoUrl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_projector_info(that, serializer);
        sse_encode_String(videoUrl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCastProjectorInfoCastVideoConstMeta,
      argValues: [that, videoUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCastProjectorInfoCastVideoConstMeta =>
      const TaskConstMeta(
        debugName: "projector_info_cast_video",
        argNames: ["that", "videoUrl"],
      );

  @override
  Future<(String, String)> crateApiCastProjectorInfoGetPositionInfo(
      {required ProjectorInfo that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_projector_info(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_record_string_string,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCastProjectorInfoGetPositionInfoConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCastProjectorInfoGetPositionInfoConstMeta =>
      const TaskConstMeta(
        debugName: "projector_info_get_position_info",
        argNames: ["that"],
      );

  @override
  Future<(BigInt, BigInt)> crateApiCastProjectorInfoGetPositionInfoSec(
      {required ProjectorInfo that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_projector_info(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_record_u_64_u_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCastProjectorInfoGetPositionInfoSecConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCastProjectorInfoGetPositionInfoSecConstMeta =>
      const TaskConstMeta(
        debugName: "projector_info_get_position_info_sec",
        argNames: ["that"],
      );

  @override
  Future<TransportState> crateApiCastProjectorInfoGetTransportInfo(
      {required ProjectorInfo that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_projector_info(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_transport_state,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCastProjectorInfoGetTransportInfoConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCastProjectorInfoGetTransportInfoConstMeta =>
      const TaskConstMeta(
        debugName: "projector_info_get_transport_info",
        argNames: ["that"],
      );

  @override
  Future<int> crateApiCastProjectorInfoGetVolume(
      {required ProjectorInfo that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_projector_info(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_8,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCastProjectorInfoGetVolumeConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCastProjectorInfoGetVolumeConstMeta =>
      const TaskConstMeta(
        debugName: "projector_info_get_volume",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiCastProjectorInfoPause({required ProjectorInfo that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_projector_info(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCastProjectorInfoPauseConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCastProjectorInfoPauseConstMeta =>
      const TaskConstMeta(
        debugName: "projector_info_pause",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiCastProjectorInfoPlay({required ProjectorInfo that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_projector_info(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCastProjectorInfoPlayConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCastProjectorInfoPlayConstMeta =>
      const TaskConstMeta(
        debugName: "projector_info_play",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiCastProjectorInfoSeek(
      {required ProjectorInfo that, required String targetTime}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_projector_info(that, serializer);
        sse_encode_String(targetTime, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCastProjectorInfoSeekConstMeta,
      argValues: [that, targetTime],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCastProjectorInfoSeekConstMeta =>
      const TaskConstMeta(
        debugName: "projector_info_seek",
        argNames: ["that", "targetTime"],
      );

  @override
  Future<void> crateApiCastProjectorInfoSetMute(
      {required ProjectorInfo that, required bool mute}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_projector_info(that, serializer);
        sse_encode_bool(mute, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCastProjectorInfoSetMuteConstMeta,
      argValues: [that, mute],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCastProjectorInfoSetMuteConstMeta =>
      const TaskConstMeta(
        debugName: "projector_info_set_mute",
        argNames: ["that", "mute"],
      );

  @override
  Future<void> crateApiCastProjectorInfoSetVolume(
      {required ProjectorInfo that, required int volume}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_projector_info(that, serializer);
        sse_encode_u_8(volume, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCastProjectorInfoSetVolumeConstMeta,
      argValues: [that, volume],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCastProjectorInfoSetVolumeConstMeta =>
      const TaskConstMeta(
        debugName: "projector_info_set_volume",
        argNames: ["that", "volume"],
      );

  @override
  Future<void> crateApiCastProjectorInfoStop({required ProjectorInfo that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_projector_info(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCastProjectorInfoStopConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCastProjectorInfoStopConstMeta =>
      const TaskConstMeta(
        debugName: "projector_info_stop",
        argNames: ["that"],
      );

  @override
  Future<List<ProjectorInfo>> crateApiCastScanProjectors(
      {required BigInt timeoutSecs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_64(timeoutSecs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_projector_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCastScanProjectorsConstMeta,
      argValues: [timeoutSecs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCastScanProjectorsConstMeta => const TaskConstMeta(
        debugName: "scan_projectors",
        argNames: ["timeoutSecs"],
      );

  @override
  Future<void> crateApiCastWakeOnLan({required String macAddress}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(macAddress, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCastWakeOnLanConstMeta,
      argValues: [macAddress],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCastWakeOnLanConstMeta => const TaskConstMeta(
        debugName: "wake_on_lan",
        argNames: ["macAddress"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ProjectorInfo dco_decode_box_autoadd_projector_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_projector_info(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProjectorInfo> dco_decode_list_projector_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_projector_info).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ProjectorInfo dco_decode_projector_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ProjectorInfo(
      friendlyName: dco_decode_String(arr[0]),
      ip: dco_decode_String(arr[1]),
      locationXmlUrl: dco_decode_String(arr[2]),
      avTransportUrl: dco_decode_opt_String(arr[3]),
      renderingControlUrl: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  (BigInt, BigInt) dco_decode_record_u_64_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_u_64(arr[0]),
      dco_decode_u_64(arr[1]),
    );
  }

  @protected
  TransportState dco_decode_transport_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TransportState.values[raw as int];
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ProjectorInfo sse_decode_box_autoadd_projector_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_projector_info(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProjectorInfo> sse_decode_list_projector_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProjectorInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_projector_info(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProjectorInfo sse_decode_projector_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_friendlyName = sse_decode_String(deserializer);
    var var_ip = sse_decode_String(deserializer);
    var var_locationXmlUrl = sse_decode_String(deserializer);
    var var_avTransportUrl = sse_decode_opt_String(deserializer);
    var var_renderingControlUrl = sse_decode_opt_String(deserializer);
    return ProjectorInfo(
        friendlyName: var_friendlyName,
        ip: var_ip,
        locationXmlUrl: var_locationXmlUrl,
        avTransportUrl: var_avTransportUrl,
        renderingControlUrl: var_renderingControlUrl);
  }

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (BigInt, BigInt) sse_decode_record_u_64_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_u_64(deserializer);
    var var_field1 = sse_decode_u_64(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  TransportState sse_decode_transport_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TransportState.values[inner];
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_projector_info(
      ProjectorInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_projector_info(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_projector_info(
      List<ProjectorInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_projector_info(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_projector_info(ProjectorInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.friendlyName, serializer);
    sse_encode_String(self.ip, serializer);
    sse_encode_String(self.locationXmlUrl, serializer);
    sse_encode_opt_String(self.avTransportUrl, serializer);
    sse_encode_opt_String(self.renderingControlUrl, serializer);
  }

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_record_u_64_u_64(
      (BigInt, BigInt) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.$1, serializer);
    sse_encode_u_64(self.$2, serializer);
  }

  @protected
  void sse_encode_transport_state(
      TransportState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
